site_name: Gameyfin Docs (beta)
site_url: https://gameyfin.github.io
theme:
  name: material
  logo: assets/logo.svg
  favicon: assets/logo.svg
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: purple
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: blue
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
  font:
    code: JetBrains Mono
  features:
    - navigation.footer
    - search.suggest
    - search.highlight

repo_url: https://github.com/gameyfin/gameyfin/tree/v2
repo_name: gameyfin
copyright: Copyright &copy; <script>document.write(new Date().getFullYear())</script> <a href="https://github.com/grimsi">grimsi</a> and <a href="https://github.com/gameyfin/gameyfin/graphs/contributors">contributors</a>

plugins:
  - search

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details