version: "3"
services:
  gameyfin:
    image: grimsi/gameyfin:v2
    container_name: gameyfin
    environment:
      PLACEHOLDER: ""
    volumes:
      - <path to your game library>:/opt/gameyfin-library
    ports:
      - "8080:8080"
